name: hf_ai_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.2

flutter_native_splash:
  image: assets/images/splash.png
  color: "#1C2C39"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
